name: ci/cd vercel
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  stage: 
    runs-on: ubuntu-latest
    environment:
      name: stage
      url: nextjs-six-iota-83.vercel.app
    steps:
      - uses: actions/checkout@v2
      - name: deploy to vercel      
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required 
          vercel-args: '--prod'
        

  prod: 
    runs-on: ubuntu-latest
    needs: stage
    environment:
      name: prod
      url: boilerplate-web-prod.vercel.app
    steps:
      - uses: actions/checkout@v2
      - name: deploy to vercel      
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required 
          vercel-args: '--prod'
